# Generated by Django 2.0.1 on 2018-03-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_site', '0003_auto_20180321_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
