# Generated by Django 2.0.1 on 2018-03-24 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_site', '0004_auto_20180321_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_site.Article')),
            ],
        ),
    ]
