# Generated by Django 2.0.1 on 2018-03-24 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_site', '0005_highlited'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Highlited',
            new_name='Highlighted',
        ),
    ]
