# Generated by Django 2.0.1 on 2018-03-25 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_site', '0007_auto_20180324_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='article_site.Regions'),
        ),
    ]
