# Generated by Django 2.0.1 on 2018-03-25 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_site', '0008_auto_20180325_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='model_pic',
            field=models.ImageField(default='static/img/empty.png', upload_to='static/articles/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article_site.Regions'),
        ),
    ]
